# Site settings
title: "Sparrow AI Tech"
description: "Custom AI/ML Solutions, Cybersecurity & IT Services"
baseurl: ""
url: "https://sparesparrow.github.io/sparrow-ai-tech"

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-hacker

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - .gitignore
  - .github/

# Include files that start with underscore
include:
  - _headers
  - _redirects

# Collections for articles
collections:
  articles:
    output: true
    permalink: /:collection/:name/

# Language settings
languages: ["cs", "en"]
default_lang: "cs"

# Defaults
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
  - scope:
      path: "articles"
    values:
      sitemap: true

# SEO and social
author: "Sparrow AI Tech"
twitter:
  username: sparrowaitech
  card: summary_large_image

social:
  name: Sparrow AI Tech
  links:
    - https://github.com/sparesparrow

# Analytics (add your tracking ID)
google_analytics: ""

# Security headers
webrick:
  headers:
    X-Frame-Options: DENY
    X-Content-Type-Options: nosniff
