name: User Story
description: Create a new user story for a feature or improvement.
title: "[User Story]: "
labels: ["type:feature", "user story"]
body:
  - type: input
    id: user-role
    attributes:
      label: User Role
      description: Who is the user or persona?
      placeholder: e.g., developer, end user, admin
    validations:
      required: true
  - type: input
    id: goal
    attributes:
      label: Goal
      description: What does the user want to achieve?
      placeholder: e.g., generate diagrams from text
    validations:
      required: true
  - type: input
    id: reason
    attributes:
      label: Reason
      description: Why does the user want this? (What is the value?)
      placeholder: e.g., to automate documentation
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the conditions that must be met for this story to be complete.
      placeholder: |
        - [ ] Diagram is generated from natural language
        - [ ] SVG output is sanitized
      value: |
        - [ ] 
    validations:
      required: true
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any extra context, links, or related issues/PRs.
      placeholder: e.g., Related to #123 