name: Browser E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  browser-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Serve Jekyll site
        run: bundle exec jekyll serve --detach

      - name: Run Puppeteer browser tests
        run: npm run browser-test

      - name: Upload screenshots (if any)
        uses: actions/upload-artifact@v3
        with:
          name: browser-screenshots
          path: browser-tests/*.png
