name: MCP-Mermaid Generator CI

on:
  push:
    paths: ['mcp-mermaid-generator/**']
  pull_request:
    paths: ['mcp-mermaid-generator/**']

jobs:
  mermaid-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Mermaid generator dependencies
        run: npm ci

      # ---------- 🐍  PYTHON SECTION ----------
      - name: Run Python tests (if present)
        if: ${{ hashFiles('mcp-mermaid-generator/tests/**') != '' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pytest
        if: ${{ hashFiles('mcp-mermaid-generator/tests/**') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Execute pytest suite
        if: ${{ hashFiles('mcp-mermaid-generator/tests/**') != '' }}
        run: pytest mcp-mermaid-generator/tests
