name: MCP Mermaid Generator CI

on:
  push:
    paths: 
      - 'mcp-mermaid-generator/**'
  pull_request:
    paths: 
      - 'mcp-mermaid-generator/**'

jobs:
  test-mermaid-generator:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [[ -f "mcp-mermaid-generator/requirements.txt" ]]; then
            pip install -r mcp-mermaid-generator/requirements.txt
          fi
          
      - name: Run Python tests
        run: |
          if [[ -d "mcp-mermaid-generator/tests" ]]; then
            cd mcp-mermaid-generator
            python -m pytest tests/ -v
          else
            echo "ℹ️ No tests found in mcp-mermaid-generator/tests"
          fi
